import { useState, useMemo } from 'react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'
import { Upload, Download, Zap } from 'lucide-react'

export default function SParamVizPanel() {
  const [fileLoaded, setFileLoaded] = useState(false)
  const [fileName, setFileName] = useState('')
  const [sparamData, setSparamData] = useState<any[]>([])
  const [viewMode, setViewMode] = useState<'mag' | 'phase'>('mag')
  const [selectedTraces, setSelectedTraces] = useState<string[]>(['S21', 'S11'])
  const [simMode, setSimMode] = useState<'upload' | 'simulate'>('upload')
  const [simComponent, setSimComponent] = useState('mzi')
  const [simParams, setSimParams] = useState({ length: 2.0, vpi_l: 2.5, loss: 3.0 })

  const generateSimData = (component: string, params: any) => {
    const points: any[] = []
    for (let f = 1; f <= 67; f += 0.5) {
      let s21_dB = 0, s11_dB = -15, s21_phase = 0, s11_phase = 0

      if (component === 'mzi') {
        const bw = 40 / (params.length || 2)
        const rolloff = 1 / Math.sqrt(1 + (f / bw) ** 4)
        s21_dB = -(params.loss || 3) + 20 * Math.log10(rolloff)
        s11_dB = -20 + 5 * Math.log10(1 + (f / bw) ** 2)
        s21_phase = -f * (params.length || 2) * 10
        s11_phase = 90 + f * 2
      } else if (component === 'ring') {
        const fsr = 10
        const resonance = Math.sin(Math.PI * f / fsr) ** 2
        s21_dB = 10 * Math.log10(Math.max(0.001, resonance))
        s11_dB = 10 * Math.log10(Math.max(0.001, 1 - resonance * 0.9))
        s21_phase = -180 * Math.sin(2 * Math.PI * f / fsr)
        s11_phase = 90 - 45 * Math.cos(2 * Math.PI * f / fsr)
      } else if (component === 'coupler') {
        const kappa = 0.5
        s21_dB = 10 * Math.log10(1 - kappa) - 0.1
        s11_dB = -25 - f * 0.05
        const s31_dB = 10 * Math.log10(kappa) - 0.1
        s21_phase = -f * 5
        s11_phase = 180
        points.push({ freq: f, S21: parseFloat(s21_dB.toFixed(2)), S11: parseFloat(s11_dB.toFixed(2)), S31: parseFloat(s31_dB.toFixed(2)), S21_phase: parseFloat(s21_phase.toFixed(1)), S11_phase: parseFloat(s11_phase.toFixed(1)), S31_phase: parseFloat((s21_phase - 90).toFixed(1)) })
        continue
      } else {
        const bw3dB = 50
        const resp = 0.9 * (1 / Math.sqrt(1 + (f / bw3dB) ** 2))
        s21_dB = 20 * Math.log10(resp)
        s11_dB = -12 + 3 * Math.log10(1 + (f / bw3dB) ** 2)
        s21_phase = -Math.atan(f / bw3dB) * 180 / Math.PI
        s11_phase = 45 + f * 0.5
      }

      points.push({ freq: f, S21: parseFloat(s21_dB.toFixed(2)), S11: parseFloat(s11_dB.toFixed(2)), S21_phase: parseFloat(s21_phase.toFixed(1)), S11_phase: parseFloat(s11_phase.toFixed(1)) })
    }
    return points
  }

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    setFileName(file.name)
    const reader = new FileReader()
    reader.onload = (evt) => {
      const text = evt.target?.result as string
      const parsed = parseTouchstone(text)
      setSparamData(parsed)
      setFileLoaded(true)
      if (parsed.length > 0) {
        setSelectedTraces(Object.keys(parsed[0]).filter((k) => k !== 'freq' && !k.includes('phase')))
      }
    }
    reader.readAsText(file)
  }

  const parseTouchstone = (text: string): any[] => {
    const lines = text.split('\n').filter((l) => l.trim() && !l.startsWith('!') && !l.startsWith('#'))
    const data: any[] = []
    for (const line of lines) {
      const parts = line.trim().split(/\s+/).map(Number)
      if (parts.length >= 3 && !isNaN(parts[0])) {
        const point: any = { freq: parts[0] }
        if (parts.length >= 9) {
          point.S11 = parts[1]; point.S11_phase = parts[2]
          point.S21 = parts[3]; point.S21_phase = parts[4]
          point.S12 = parts[5]; point.S12_phase = parts[6]
          point.S22 = parts[7]; point.S22_phase = parts[8]
        } else if (parts.length >= 5) {
          point.S11 = parts[1]; point.S11_phase = parts[2]
          point.S21 = parts[3]; point.S21_phase = parts[4]
        }
        data.push(point)
      }
    }
    return data
  }

  const handleSimulate = () => {
    const data = generateSimData(simComponent, simParams)
    setSparamData(data)
    setFileLoaded(true)
    setFileName(`${simComponent}_simulated.s2p`)
    setSelectedTraces(Object.keys(data[0]).filter((k) => k !== 'freq' && !k.includes('phase')))
  }

  const exportS2P = () => {
    if (sparamData.length === 0) return
    let content = `! Touchstone S-Parameter File\n! Generated by: 光芯片互动平台\n! Component: ${simComponent}\n# GHz S dB R 50\n`
    for (const p of sparamData) {
      const s11 = p.S11 ?? -20, s11p = p.S11_phase ?? 0, s21 = p.S21 ?? -3, s21p = p.S21_phase ?? -90
      content += `${p.freq.toFixed(4)}\t${s11.toFixed(3)}\t${s11p.toFixed(1)}\t${s21.toFixed(3)}\t${s21p.toFixed(1)}\t${s21.toFixed(3)}\t${s21p.toFixed(1)}\t${s11.toFixed(3)}\t${s11p.toFixed(1)}\n`
    }
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = fileName.replace(/\.[^.]+$/, '') + '.s2p'; a.click()
    URL.revokeObjectURL(url)
  }

  const chartData = useMemo(() => sparamData, [sparamData])
  const traceColors = ['#3b82f6', '#ef4444', '#22c55e', '#f97316', '#8b5cf6', '#ec4899']
  const allTraces = sparamData.length > 0 ? Object.keys(sparamData[0]).filter((k) => k !== 'freq' && (viewMode === 'phase' ? k.includes('phase') : !k.includes('phase'))) : []

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">S 参数可视化</h1>
      <p className="text-gray-500 mb-8">上传 Touchstone 文件或 GDS → 仿真 → 幅频/相频图表 → 导出 .s2p</p>

      {/* Mode Switch */}
      <div className="flex gap-3 mb-6">
        <button onClick={() => setSimMode('upload')} className={`px-4 py-2 rounded-lg text-sm font-medium ${simMode === 'upload' ? 'bg-indigo-600 text-white' : 'bg-white border border-gray-200 text-gray-600'}`}>
          📁 上传 S 参数文件
        </button>
        <button onClick={() => setSimMode('simulate')} className={`px-4 py-2 rounded-lg text-sm font-medium ${simMode === 'simulate' ? 'bg-indigo-600 text-white' : 'bg-white border border-gray-200 text-gray-600'}`}>
          🔬 GDS → 仿真生成
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Input */}
        <div className="bg-white rounded-xl shadow-md p-6 border border-gray-100">
          {simMode === 'upload' ? (
            <>
              <h3 className="font-semibold text-gray-900 mb-4">上传 Touchstone 文件</h3>
              <div className="border-2 border-dashed border-gray-200 rounded-lg p-6 text-center mb-4">
                <Upload className="h-8 w-8 text-gray-300 mx-auto mb-2" />
                <p className="text-sm text-gray-500 mb-2">拖拽或点击上传</p>
                <p className="text-xs text-gray-400 mb-3">支持 .s2p / .s4p / .csv</p>
                <input type="file" accept=".s2p,.s4p,.s1p,.csv,.txt" onChange={handleFileUpload} className="text-xs" />
              </div>
              {fileName && <p className="text-xs text-green-600">✓ 已加载: {fileName} ({sparamData.length} 点)</p>}
            </>
          ) : (
            <>
              <h3 className="font-semibold text-gray-900 mb-4">GDS → 仿真</h3>
              <div className="space-y-4">
                <div>
                  <label className="text-sm text-gray-600 block mb-1">器件类型</label>
                  <select value={simComponent} onChange={(e) => setSimComponent(e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm">
                    <option value="mzi">MZI 调制器</option>
                    <option value="ring">微环谐振器</option>
                    <option value="coupler">定向耦合器</option>
                    <option value="ge-pd">Ge 光电探测器</option>
                  </select>
                </div>
                {simComponent === 'mzi' && (
                  <>
                    <div><label className="text-xs text-gray-500">臂长 (mm)</label><input type="number" value={simParams.length} onChange={(e) => setSimParams({ ...simParams, length: Number(e.target.value) })} className="w-full px-3 py-1.5 border border-gray-300 rounded text-sm" step={0.5} /></div>
                    <div><label className="text-xs text-gray-500">VπL (V·cm)</label><input type="number" value={simParams.vpi_l} onChange={(e) => setSimParams({ ...simParams, vpi_l: Number(e.target.value) })} className="w-full px-3 py-1.5 border border-gray-300 rounded text-sm" step={0.1} /></div>
                    <div><label className="text-xs text-gray-500">插入损耗 (dB)</label><input type="number" value={simParams.loss} onChange={(e) => setSimParams({ ...simParams, loss: Number(e.target.value) })} className="w-full px-3 py-1.5 border border-gray-300 rounded text-sm" step={0.5} /></div>
                  </>
                )}
                <div className="border-2 border-dashed border-orange-200 rounded-lg p-4 text-center bg-orange-50">
                  <p className="text-xs text-orange-700 mb-2">可选：上传 GDS 文件自动提取结构</p>
                  <input type="file" accept=".gds,.gds2" className="text-xs" />
                </div>
                <button onClick={handleSimulate} className="w-full py-2.5 bg-indigo-600 text-white rounded-lg text-sm font-medium hover:bg-indigo-700">运行仿真</button>
              </div>
            </>
          )}

          {fileLoaded && (
            <div className="mt-4 pt-4 border-t border-gray-100">
              <p className="text-xs font-medium text-gray-500 mb-2">显示曲线</p>
              <div className="flex flex-wrap gap-2">
                {allTraces.map((trace, i) => (
                  <button key={trace} onClick={() => setSelectedTraces(selectedTraces.includes(trace) ? selectedTraces.filter((t) => t !== trace) : [...selectedTraces, trace])}
                    className={`text-xs px-2 py-1 rounded border ${selectedTraces.includes(trace) ? 'border-indigo-500 bg-indigo-50 text-indigo-700' : 'border-gray-200 text-gray-400'}`}>
                    <span className="inline-block w-2 h-2 rounded-full mr-1" style={{ backgroundColor: traceColors[i % traceColors.length] }} />{trace}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Center+Right: Charts */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex gap-2">
            <button onClick={() => setViewMode('mag')} className={`px-3 py-1.5 rounded text-xs font-medium ${viewMode === 'mag' ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-600'}`}>幅频响应 (dB)</button>
            <button onClick={() => setViewMode('phase')} className={`px-3 py-1.5 rounded text-xs font-medium ${viewMode === 'phase' ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-600'}`}>相频响应 (°)</button>
            {fileLoaded && (
              <button onClick={exportS2P} className="ml-auto px-3 py-1.5 rounded text-xs font-medium bg-green-600 text-white hover:bg-green-700 flex items-center gap-1">
                <Download className="h-3 w-3" /> 导出 .s2p
              </button>
            )}
          </div>

          {fileLoaded && chartData.length > 0 ? (
            <div className="bg-white rounded-xl shadow-md p-6 border border-gray-100">
              <h3 className="font-semibold text-gray-900 mb-2 text-sm">
                {viewMode === 'mag' ? '幅频响应 |S| (dB)' : '相频响应 ∠S (°)'}
                <span className="text-xs text-gray-400 ml-2">— {fileName}</span>
              </h3>
              <ResponsiveContainer width="100%" height={350}>
                <LineChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis dataKey="freq" label={{ value: 'Frequency (GHz)', position: 'bottom', offset: -5 }} tick={{ fontSize: 10 }} />
                  <YAxis label={{ value: viewMode === 'mag' ? 'Magnitude (dB)' : 'Phase (°)', angle: -90, position: 'insideLeft' }} tick={{ fontSize: 10 }} />
                  <Tooltip />
                  <Legend />
                  {selectedTraces.map((trace, i) => (
                    <Line key={trace} type="monotone" dataKey={trace} stroke={traceColors[i % traceColors.length]} dot={false} strokeWidth={2} name={trace} />
                  ))}
                </LineChart>
              </ResponsiveContainer>
            </div>
          ) : (
            <div className="bg-white rounded-xl shadow-md p-6 border border-gray-100 flex items-center justify-center h-[400px] text-gray-400">
              <div className="text-center">
                <Zap className="h-12 w-12 mx-auto mb-3 opacity-30" />
                <p className="text-sm">上传 Touchstone 文件或运行仿真后<br />此处显示幅频/相频图表</p>
              </div>
            </div>
          )}

          {fileLoaded && chartData.length > 0 && (
            <div className="bg-white rounded-xl shadow-md p-6 border border-gray-100">
              <h3 className="font-semibold text-gray-900 mb-3 text-sm">数据预览 (前 10 点)</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-gray-200">
                      <th className="py-1.5 px-2 text-left font-medium text-gray-600">Freq (GHz)</th>
                      {Object.keys(chartData[0]).filter((k) => k !== 'freq').map((k) => (
                        <th key={k} className="py-1.5 px-2 text-right font-medium text-gray-600">{k}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {chartData.slice(0, 10).map((row, i) => (
                      <tr key={i} className={i % 2 === 0 ? 'bg-gray-50' : ''}>
                        <td className="py-1 px-2 font-mono">{row.freq.toFixed(2)}</td>
                        {Object.keys(row).filter((k) => k !== 'freq').map((k) => (
                          <td key={k} className="py-1 px-2 text-right font-mono">{typeof row[k] === 'number' ? row[k].toFixed(2) : row[k]}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="text-xs text-gray-400 mt-2">共 {chartData.length} 个数据点</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
